table Sheet1
	lineageTag: 67cff1f5-62ca-4e15-b5f5-3fa1321b9ddf

	column Stichtag
		dataType: dateTime
		formatString: Long Date
		lineageTag: bb30be8d-14e4-4cd8-8c7b-5eabfd281719
		summarizeBy: none
		sourceColumn: Stichtag

		variation Variation
			isDefault
			relationship: be7315f1-5ac9-4257-8ef5-9996d7c542dc
			defaultHierarchy: LocalDateTable_59d7a934-1770-4e42-8be8-e9057fb5d26a.Datumshierarchie

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column BuKr
		dataType: string
		lineageTag: de767de7-3b4e-4d99-b4ec-24c68e443bde
		summarizeBy: none
		sourceColumn: BuKr

		annotation SummarizationSetBy = Automatic

	column Sachkonto
		dataType: int64
		formatString: 0
		lineageTag: f2870dbf-9dd7-43dc-a6c0-4aaa95f55ab5
		summarizeBy: sum
		sourceColumn: Sachkonto

		annotation SummarizationSetBy = Automatic

	column Sachkonto_1
		dataType: string
		lineageTag: 5e74ce2e-3ef4-49e0-9766-7b429c815314
		summarizeBy: none
		sourceColumn: Sachkonto_1

		annotation SummarizationSetBy = Automatic

	column Gruppen_Identnummer
		dataType: string
		lineageTag: a6e7c8ba-b7b4-412e-97c3-64e5752afd46
		summarizeBy: none
		sourceColumn: Gruppen_Identnummer

		annotation SummarizationSetBy = Automatic

	column 'Bez. Gruppe'
		dataType: string
		lineageTag: 88108933-7490-425e-8402-dc4427f3848a
		summarizeBy: none
		sourceColumn: Bez. Gruppe

		annotation SummarizationSetBy = Automatic

	column 'Group LEI'
		dataType: string
		lineageTag: 3b3d61ed-92c4-4419-9aa6-14bc334bde5e
		summarizeBy: none
		sourceColumn: Group LEI

		annotation SummarizationSetBy = Automatic

	column 'Ris.zuteilung GrEmittent'
		dataType: int64
		formatString: 0
		lineageTag: 8a0a230e-2a47-47b3-80ad-ea212e8abc97
		summarizeBy: sum
		sourceColumn: Ris.zuteilung GrEmittent

		annotation SummarizationSetBy = Automatic

	column 'Text Risiko GrEmittent'
		dataType: string
		lineageTag: 0a861035-f35c-4382-9cd6-b3d81075a0d1
		summarizeBy: none
		sourceColumn: Text Risiko GrEmittent

		annotation SummarizationSetBy = Automatic

	column Hauptdarlehenspartner
		dataType: string
		lineageTag: 927da4ad-ad8a-4ced-b754-605866997a58
		summarizeBy: none
		sourceColumn: Hauptdarlehenspartner

		annotation SummarizationSetBy = Automatic

	column Partner
		dataType: string
		lineageTag: 1de9c40b-c4be-4e6e-a2b6-41b7ecd708ab
		summarizeBy: none
		sourceColumn: Partner

		annotation SummarizationSetBy = Automatic

	column Land
		dataType: string
		lineageTag: 4bac9dd2-a503-44a5-88b4-0ee9b372c9c1
		summarizeBy: none
		sourceColumn: Land

		annotation SummarizationSetBy = Automatic

	column LEI-Id
		dataType: string
		lineageTag: d2cc4d24-7507-4817-be5b-4322f2747141
		summarizeBy: none
		sourceColumn: LEI-Id

		annotation SummarizationSetBy = Automatic

	column 'Ris.zuteilung Emittent'
		dataType: int64
		formatString: 0
		lineageTag: 6cbde8aa-2fdb-47a8-a32d-65bb06d83b7f
		summarizeBy: sum
		sourceColumn: Ris.zuteilung Emittent

		annotation SummarizationSetBy = Automatic

	column 'Text Risiko Emittent'
		dataType: string
		lineageTag: 7cdaa674-9782-4067-a128-f92d8c920920
		summarizeBy: none
		sourceColumn: Text Risiko Emittent

		annotation SummarizationSetBy = Automatic

	column 'IGT is Considered'
		dataType: int64
		formatString: 0
		lineageTag: ee4b35e8-db85-4bc7-bbb6-57b03aa05733
		summarizeBy: sum
		sourceColumn: IGT is Considered

		annotation SummarizationSetBy = Automatic

	column 'Is Considered'
		dataType: string
		lineageTag: 629f392e-06de-4aac-a2af-11677d06d6cf
		summarizeBy: none
		sourceColumn: Is Considered

		annotation SummarizationSetBy = Automatic

	column VBUND
		dataType: string
		lineageTag: 7ebb51b8-c5fb-45cc-ae64-e05f65dfbb1b
		summarizeBy: none
		sourceColumn: VBUND

		annotation SummarizationSetBy = Automatic

	column Versicherungssparte
		dataType: string
		lineageTag: 71dd3f06-9ca5-46a1-9457-be0c691ca25b
		summarizeBy: none
		sourceColumn: Versicherungssparte

		annotation SummarizationSetBy = Automatic

	column Stock-KZ
		dataType: string
		lineageTag: b67eeb4a-fc27-4842-873e-07ab3ded2490
		summarizeBy: none
		sourceColumn: Stock-KZ

		annotation SummarizationSetBy = Automatic

	column PArt
		dataType: string
		lineageTag: c7b62b0f-8665-4dc9-a1d8-8ae9a43c187d
		summarizeBy: none
		sourceColumn: PArt

		annotation SummarizationSetBy = Automatic

	column Produktart
		dataType: string
		lineageTag: 9a3e1656-8639-42b8-909a-eb1444e13744
		summarizeBy: none
		sourceColumn: Produktart

		annotation SummarizationSetBy = Automatic

	column Darlehensart
		dataType: int64
		formatString: 0
		lineageTag: c5a0ccf5-b3ab-4190-9e4f-3bbee18675de
		summarizeBy: sum
		sourceColumn: Darlehensart

		annotation SummarizationSetBy = Automatic

	column Darlehensart_2
		dataType: string
		lineageTag: 71e2d971-c476-4c22-91dc-3a8659d00412
		summarizeBy: none
		sourceColumn: Darlehensart_2

		annotation SummarizationSetBy = Automatic

	column Vertragsnummer
		dataType: int64
		formatString: 0
		lineageTag: 5508fd82-119c-4572-9e4d-0f4af59cd4a9
		summarizeBy: sum
		sourceColumn: Vertragsnummer

		annotation SummarizationSetBy = Automatic

	column 'LFZ Beginn'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 40c0a396-e760-4987-b2e1-9f25b5aef4d1
		summarizeBy: none
		sourceColumn: LFZ Beginn

		variation Variation
			isDefault
			relationship: dcc09e33-5599-4c71-9b16-b0cde8a11e68
			defaultHierarchy: LocalDateTable_19c922ca-54b2-41c4-9ecc-1d51a046b52a.Datumshierarchie

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'LFZ Ende'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 46b81bac-53c8-43d0-8a51-37796782a1e5
		summarizeBy: none
		sourceColumn: LFZ Ende

		variation Variation
			isDefault
			relationship: 5437da89-66dd-43e9-aa83-468d2af717b1
			defaultHierarchy: LocalDateTable_3895ef99-9a0f-40e0-82b4-68f8458e2e28.Datumshierarchie

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Zinssatz
		dataType: double
		lineageTag: 7a13bbea-baa3-45bf-97c1-5c93289ac00c
		summarizeBy: none
		sourceColumn: Zinssatz

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Zinsberech.Methode'
		dataType: string
		lineageTag: 71ecc773-5574-46c4-808d-688a3a87a8de
		summarizeBy: none
		sourceColumn: Zinsberech.Methode

		annotation SummarizationSetBy = Automatic

	column Zinsberechnungsmethode
		dataType: string
		lineageTag: 45d91565-b6f5-403b-a8c8-1b9682e9a08a
		summarizeBy: none
		sourceColumn: Zinsberechnungsmethode

		annotation SummarizationSetBy = Automatic

	column Zinsberechnungsmethode_3
		dataType: int64
		formatString: 0
		lineageTag: 9aa6ee6f-5639-4f1c-8cbc-99137bc2a35b
		summarizeBy: sum
		sourceColumn: Zinsberechnungsmethode_3

		annotation SummarizationSetBy = Automatic

	column 'Zinskondition Rhythmus'
		dataType: int64
		formatString: 0
		lineageTag: 926af270-ef8e-491a-9f54-bc45de09d732
		summarizeBy: sum
		sourceColumn: Zinskondition Rhythmus

		annotation SummarizationSetBy = Automatic

	column Tilgungsart
		dataType: int64
		formatString: 0
		lineageTag: 03fbee71-8036-427c-ac44-2a75ed7b60bd
		summarizeBy: sum
		sourceColumn: Tilgungsart

		annotation SummarizationSetBy = Automatic

	column Tilgungsart_4
		dataType: string
		lineageTag: 6f4b026c-12eb-479f-b091-00e6ac05f244
		summarizeBy: none
		sourceColumn: Tilgungsart_4

		annotation SummarizationSetBy = Automatic

	column 'Tilgungskondition Rhythmus'
		dataType: int64
		formatString: 0
		lineageTag: 84bbf0c5-556a-4ab0-860e-d40656a55fcd
		summarizeBy: sum
		sourceColumn: Tilgungskondition Rhythmus

		annotation SummarizationSetBy = Automatic

	column BestWhrg
		dataType: string
		lineageTag: 5c67e028-fed8-47b4-a9c6-c0424668826c
		summarizeBy: none
		sourceColumn: BestWhrg

		annotation SummarizationSetBy = Automatic

	column 'Aktuelles Vertragskapital BW'
		dataType: double
		lineageTag: 56a29c69-c784-4b39-a043-67f7ef9faa06
		summarizeBy: sum
		sourceColumn: Aktuelles Vertragskapital BW

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Restkapital BW'
		dataType: double
		lineageTag: 41509a25-4d60-45b5-9bed-69baa2096eb5
		summarizeBy: sum
		sourceColumn: Restkapital BW

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Effektivkapital BW'
		dataType: double
		lineageTag: f53c612e-efdc-4a9d-bbde-2da4c0377615
		summarizeBy: sum
		sourceColumn: Effektivkapital BW

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Buchwert in BW'
		dataType: double
		lineageTag: 2e2e372a-44c2-449d-bf3f-95850a806a60
		summarizeBy: sum
		sourceColumn: Buchwert in BW

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Off. Tilg. BW'
		dataType: double
		lineageTag: ceede1a0-229e-4dd3-aee0-f4a148a10994
		summarizeBy: sum
		sourceColumn: Off. Tilg. BW

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Letzte gebuchte Abgrenzung'
		dataType: double
		lineageTag: 8667004b-475e-45fd-9b3b-ec07ff7519f1
		summarizeBy: sum
		sourceColumn: Letzte gebuchte Abgrenzung

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Barwert
		dataType: int64
		formatString: 0
		lineageTag: f82e7e48-04dc-4917-aa14-a21cb4c6b667
		summarizeBy: sum
		sourceColumn: Barwert

		annotation SummarizationSetBy = Automatic

	column Währung
		dataType: string
		lineageTag: 504b4589-5a14-4b8f-a9f4-edbb491beb0a
		summarizeBy: none
		sourceColumn: Währung

		annotation SummarizationSetBy = Automatic

	column 'Restkapital HW'
		dataType: double
		lineageTag: e349ef2b-65ca-474f-be5d-179a64193d93
		summarizeBy: sum
		sourceColumn: Restkapital HW

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Effektivkapital HW'
		dataType: double
		lineageTag: a1424b23-9e4e-4ab7-a994-b3fb8e86008e
		summarizeBy: sum
		sourceColumn: Effektivkapital HW

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Buchwert in HW'
		dataType: double
		lineageTag: 28e1e486-27bd-424b-b88f-2406d001af67
		summarizeBy: sum
		sourceColumn: Buchwert in HW

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Off. Tilg. HW'
		dataType: double
		lineageTag: 29d0acca-036c-493f-aed5-8a3c10f78f7a
		summarizeBy: sum
		sourceColumn: Off. Tilg. HW

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Accruals in LC'
		dataType: double
		lineageTag: e84bd9e1-0e8a-4ded-a1fc-f271f10dfeea
		summarizeBy: sum
		sourceColumn: Accruals in LC

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ModDuration
		dataType: int64
		formatString: 0
		lineageTag: c8b88a8c-b8fb-4d97-ae96-f03925f1b853
		summarizeBy: sum
		sourceColumn: ModDuration

		annotation SummarizationSetBy = Automatic

	column 'CIC Land'
		dataType: string
		lineageTag: 88f2d483-f5f0-497d-8bb9-d3ec00eefb33
		summarizeBy: none
		sourceColumn: CIC Land

		annotation SummarizationSetBy = Automatic

	column 'CIC Category'
		dataType: int64
		formatString: 0
		lineageTag: eddb30b2-9f69-4587-8890-4e3bed65bc74
		summarizeBy: sum
		sourceColumn: CIC Category

		annotation SummarizationSetBy = Automatic

	column 'SII valuation Method'
		dataType: string
		lineageTag: 1d9ddff2-ba59-45b9-818b-0d64be6c6320
		summarizeBy: none
		sourceColumn: SII valuation Method

		annotation SummarizationSetBy = Automatic

	column BilposSII
		dataType: int64
		formatString: 0
		lineageTag: 079a3b8e-b026-4476-ab68-2abc7ea07a8f
		summarizeBy: sum
		sourceColumn: BilposSII

		annotation SummarizationSetBy = Automatic

	column 'Bilanzposition SII'
		dataType: string
		lineageTag: 73789838-b824-4bb1-8257-c7ba59355974
		summarizeBy: none
		sourceColumn: Bilanzposition SII

		annotation SummarizationSetBy = Automatic

	column 'SePP 2.0 Gewinnbeteiligungssim'
		dataType: string
		lineageTag: f2793d64-9907-4dcd-bbe6-1cfc3b33aa9c
		summarizeBy: none
		sourceColumn: SePP 2.0 Gewinnbeteiligungssim

		annotation SummarizationSetBy = Automatic

	column POSITION_TYPE
		dataType: string
		lineageTag: d20473b5-ac18-4767-89f2-6df0b0952302
		summarizeBy: none
		sourceColumn: POSITION_TYPE

		annotation SummarizationSetBy = Automatic

	column PROD_ID
		dataType: string
		lineageTag: bb42841e-4a3c-47df-af2b-adaad86b01fc
		summarizeBy: none
		sourceColumn: PROD_ID

		annotation SummarizationSetBy = Automatic

	column 'Pled.as Collateral'
		dataType: string
		lineageTag: 26c5268b-8d75-4f50-9540-628da074917d
		summarizeBy: none
		sourceColumn: Pled.as Collateral

		annotation SummarizationSetBy = Automatic

	column 'Dom.Curr.'
		dataType: int64
		formatString: 0
		lineageTag: 5ad43b2a-c3f9-4432-879f-5db5b96b6eb8
		summarizeBy: sum
		sourceColumn: Dom.Curr.

		annotation SummarizationSetBy = Automatic

	column 'ÖNB-Nummer des Emittenten'
		dataType: string
		lineageTag: 5b49ed59-9275-43cb-9765-890a5a719554
		summarizeBy: none
		sourceColumn: ÖNB-Nummer des Emittenten

		annotation SummarizationSetBy = Automatic

	partition Sheet1 = m
		mode: import
		source =
				let
				    Quelle = Excel.Workbook(File.Contents("C:\Users\nplattner\Documents\GRAWE\S4P_ZCMLSO_202307.XLSX"), null, true),
				    Sheet1_Sheet = Quelle{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Höher gestufte Header" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Geänderter Typ" = Table.TransformColumnTypes(#"Höher gestufte Header",{{"Stichtag", type date}, {"BuKr", type text}, {"Sachkonto", Int64.Type}, {"Sachkonto_1", type text}, {"Gruppen_Identnummer", type text}, {"Bez. Gruppe", type text}, {"Group LEI", type text}, {"Ris.zuteilung GrEmittent", Int64.Type}, {"Text Risiko GrEmittent", type text}, {"Hauptdarlehenspartner", type text}, {"Partner", type text}, {"Land", type text}, {"LEI-Id", type text}, {"Ris.zuteilung Emittent", Int64.Type}, {"Text Risiko Emittent", type text}, {"IGT is Considered", Int64.Type}, {"Is Considered", type text}, {"VBUND", type text}, {"Versicherungssparte", type text}, {"Stock-KZ", type text}, {"PArt", type text}, {"Produktart", type text}, {"Darlehensart", Int64.Type}, {"Darlehensart_2", type text}, {"Vertragsnummer", Int64.Type}, {"LFZ Beginn", type date}, {"LFZ Ende", type date}, {"Zinssatz", type number}, {"Zinsberech.Methode", type text}, {"Zinsberechnungsmethode", type text}, {"Zinsberechnungsmethode_3", Int64.Type}, {"Zinskondition Rhythmus", Int64.Type}, {"Tilgungsart", Int64.Type}, {"Tilgungsart_4", type text}, {"Tilgungskondition Rhythmus", Int64.Type}, {"BestWhrg", type text}, {"Aktuelles Vertragskapital BW", type number}, {"Restkapital BW", type number}, {"Effektivkapital BW", type number}, {"Buchwert in BW", type number}, {"Off. Tilg. BW", type number}, {"Letzte gebuchte Abgrenzung", type number}, {"Barwert", Int64.Type}, {"Währung", type text}, {"Restkapital HW", type number}, {"Effektivkapital HW", type number}, {"Buchwert in HW", type number}, {"Off. Tilg. HW", type number}, {"Accruals in LC", type number}, {"ModDuration", Int64.Type}, {"CIC Land", type text}, {"CIC Category", Int64.Type}, {"SII valuation Method", type text}, {"BilposSII", Int64.Type}, {"Bilanzposition SII", type text}, {"SePP 2.0 Gewinnbeteiligungssim", type text}, {"POSITION_TYPE", type text}, {"PROD_ID", type text}, {"Pled.as Collateral", type text}, {"Dom.Curr.", Int64.Type}, {"ÖNB-Nummer des Emittenten", type text}})
				in
				    #"Geänderter Typ"

	annotation PBI_ResultType = Table

